name: Release

on:
  release:
    types: [published]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./DominionsReplayHelper.GUI/
    - name: Build
      run: dotnet build --no-restore ./DominionsReplayHelper.GUI/
    - name: Publish
      run: dotnet publish ./DominionsReplayHelper.GUI/ -o ./publish/DominionsReplayHelper/
    - name: Zip
      run: zip DominionsReplayHelperApp.zip ./publish/DominionsReplayHelper/* -r
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DominionsReplayHelper
        path: DominionsReplayHelperApp.zip
    - name: Release
      run: gh release upload ${{github.event.release.tag_name}} DominionsReplayHelperApp.zip
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

